apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-operator
  namespace: iperf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iperf-operator
  template:
    metadata:
      labels:
        name: iperf-operator
    spec:
      serviceAccountName: iperf-operator
      containers:
        - name: iperf-operator
          # Replace this with the built image name
          image: quay.io/jharrington22/iperf-operator:v0.1.21-89f608bd
          command:
          - iperf-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iperf-operator"
